-- MySQL Script generated by MySQL Workbench
-- 04/24/16 18:24:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e-learning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e-learning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e-learning` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `e-learning` ;

-- -----------------------------------------------------
-- Table `e-learning`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-learning`.`member` (
  `member_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(16) NULL COMMENT '',
  `initials` VARCHAR(6) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `surname` VARCHAR(45) NULL COMMENT '',
  `country` VARCHAR(20) NULL COMMENT '',
  `tel` VARCHAR(10) NULL COMMENT '',
  `email` VARCHAR(30) NULL COMMENT '',
  PRIMARY KEY (`member_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-learning`.`sub_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-learning`.`sub_group` (
  `group_id` VARCHAR(10) NOT NULL COMMENT '',
  `group_name` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`group_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-learning`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-learning`.`subject` (
  `subject_code` VARCHAR(10) NOT NULL COMMENT '',
  `group_id` VARCHAR(10) NOT NULL COMMENT '',
  `title` VARCHAR(200) NULL COMMENT '',
  `subtitle` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`subject_code`, `group_id`)  COMMENT '',
  INDEX `fk_subject_sub_group1_idx` (`group_id` ASC)  COMMENT '',
  CONSTRAINT `fk_subject_sub_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `e-learning`.`sub_group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-learning`.`enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-learning`.`enrollment` (
  `member_id` INT UNSIGNED NOT NULL COMMENT '',
  `subject_code` VARCHAR(10) NOT NULL COMMENT '',
  `type` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`member_id`, `subject_code`)  COMMENT '',
  INDEX `fk_enrollment_subject1_idx` (`subject_code` ASC)  COMMENT '',
  INDEX `fk_enrollment_member1_idx` (`member_id` ASC)  COMMENT '',
  CONSTRAINT `fk_enrollment_subject1`
    FOREIGN KEY (`subject_code`)
    REFERENCES `e-learning`.`subject` (`subject_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrollment_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `e-learning`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-learning`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-learning`.`section` (
  `section_id` VARCHAR(10) NOT NULL COMMENT '',
  `parent_section_id` VARCHAR(10) NOT NULL COMMENT '',
  `subject_code` VARCHAR(10) NOT NULL COMMENT '',
  `section_name` VARCHAR(100) NULL COMMENT '',
  `order` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`section_id`, `parent_section_id`, `subject_code`)  COMMENT '',
  INDEX `fk_document_subject1_idx` (`subject_code` ASC)  COMMENT '',
  INDEX `fk_section_section1_idx` (`parent_section_id` ASC)  COMMENT '',
  CONSTRAINT `fk_document_subject1`
    FOREIGN KEY (`subject_code`)
    REFERENCES `e-learning`.`subject` (`subject_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_section_section1`
    FOREIGN KEY (`parent_section_id`)
    REFERENCES `e-learning`.`section` (`section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-learning`.`content_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e-learning`.`content_page` (
  `section_id` VARCHAR(10) NOT NULL COMMENT '',
  `page_no` VARCHAR(11) NOT NULL COMMENT '',
  `content` BLOB NULL COMMENT '',
  PRIMARY KEY (`section_id`)  COMMENT '',
  CONSTRAINT `fk_content_page_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `e-learning`.`section` (`section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
